#!/bin/bash
PROGRAM_ARGS=""
JAVA_ARGS=""
for opt in "$@"
    do
      case $opt in
        -debug)
          JAVA_ARGS="$JAVA_ARGS -Xdebug -Xrunjdwp:transport=dt_socket,server=y,address=8000,suspend=y" ;;
        -dump)
          JAVA_ARGS="$JAVA_ARGS -Dgraal.Dump=Truffle:1 -Dgraal.TruffleBackgroundCompilation=false -Dgraal.TraceTruffleCompilation=true" ;;
        -disassemble)
          JAVA_ARGS="$JAVA_ARGS -XX:CompileCommand=print,*OptimizedCallTarget.callRoot -XX:CompileCommand=exclude,*OptimizedCallTarget.callRoot -Dgraal.TruffleBackgroundCompilation=false -Dgraal.TraceTruffleCompilation=true -Dgraal.TraceTruffleCompilationDetails=true" ;;
        -J*)
          opt=${opt:2}
          JAVA_ARGS="$JAVA_ARGS $opt" ;;
        *)
          PROGRAM_ARGS="$PROGRAM_ARGS $opt" ;;
      esac
    done
$GRAALVM_HOME/bin/java $JAVA_ARGS -XX:-UseJVMCIClassLoader -Dgraal.TraceTruffleCompilation=true -Dgraal.TraceTruffleTransferToInterpreter=true -Dgraal.PrintGraph=Network -Dgraal.TraceTruffleCompilation=true -Dgraal.TraceTruffleCompilationDetails=true -Dgraal.TraceTruffleCompilation=true -Dgraal.TruffleBackgroundCompilation=false -cp ./target/classes demo.Demo2 $PROGRAM_ARGS