#!/bin/bash
PROGRAM_ARGS=""
JAVA_ARGS=""
for opt in "$@"
    do
      case $opt in
        -debug)
          JAVA_ARGS="$JAVA_ARGS -Xdebug -Xrunjdwp:transport=dt_socket,server=y,address=8000,suspend=y" ;;
        -dump)
          JAVA_ARGS="$JAVA_ARGS -Dgraal.Dump=Truffle:1 -Dpolyglot.engine.TraceCompilation=true" ;;
        -disassemble)
          JAVA_ARGS="$JAVA_ARGS -server -XX:CompileCommand=print,*OptimizedCallTarget.profiledPERoot -XX:CompileCommand=exclude,*OptimizedCallTarget.callRoot" ;;
        -J*)
          opt=${opt:2}
          JAVA_ARGS="$JAVA_ARGS $opt" ;;
        *)
          PROGRAM_ARGS="$PROGRAM_ARGS $opt" ;;
      esac
    done
$GRAALVM_HOME/bin/java $JAVA_ARGS -XX:-UseJVMCIClassLoader -XX:-UseJVMCINativeLibrary -Dpolyglot.engine.TraceTransferToInterpreter=true -Dpolyglot.engine.TraceCompilation=true -Dgraal.PrintGraph=Network -Dpolyglot.engine.BackgroundCompilation=false  -cp ./target/classes demo.Demo1 $PROGRAM_ARGS