#!/bin/bash
PROGRAM_ARGS=""
JAVA_ARGS="-Dpolyglotimpl.DisableVersionChecks=true -Dpolyglot.engine.TraceTransferToInterpreter=true --sun-misc-unsafe-memory-access=allow --enable-native-access=ALL-UNNAMED -Dpolyglot.engine.TraceCompilation=true -Djdk.graal.PrintGraph=Network -Dpolyglot.engine.MultiTier=false -Dpolyglot.engine.BackgroundCompilation=false"
for opt in "$@"
    do
      case $opt in
        -debug)
          JAVA_ARGS="$JAVA_ARGS -Xdebug -Xrunjdwp:transport=dt_socket,server=y,address=8000,suspend=y" ;;
        -dump)
          JAVA_ARGS="$JAVA_ARGS -Djdk.graal.Dump=Truffle:1 -Dpolyglot.engine.TraceCompilation=true" ;;
        -disassemble)
          JAVA_ARGS="$JAVA_ARGS -server -XX:CompileCommand=print,*OptimizedCallTarget.profiledPERoot" ;;
        -J*)
          opt=${opt:2}
          JAVA_ARGS="$JAVA_ARGS $opt" ;;
        *)
          PROGRAM_ARGS="$PROGRAM_ARGS $opt" ;;
      esac
    done

java $JAVA_ARGS -cp target/lib/*:./target/classes $PROGRAM_ARGS
